# Generated by Django 5.2.2 on 2025-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.AddField(
            model_name='agent',
            name='commission_agent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
