# Generated by Django 5.2.2 on 2025-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='paid',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='', max_length=30),
        ),
    ]
