# Generated by Django 5.2.2 on 2025-06-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_ticketsale_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='flight_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight_from', to='sales.destination'),
        ),
        migrations.AlterField(
            model_name='ticketsale',
            name='flight_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flight_to', to='sales.destination'),
        ),
    ]
