# Generated by Django 5.2.2 on 2025-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_destination_alter_ticketsale_flight_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
