# Generated by Django 5.2.2 on 2025-07-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0005_remove_ticketsale_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customer'),
        ),
    ]
