# Generated by Django 5.2.2 on 2025-07-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_ticketsale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='sales.airline'),
        ),
    ]
