# Generated by Django 5.2.4 on 2025-08-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_ticketsale_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='sales.ticketsale')),
            ],
        ),
        migrations.CreateModel(
            name='Childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='sales.ticketsale')),
            ],
        ),
        migrations.CreateModel(
            name='Infants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infants', to='sales.ticketsale')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from', to='sales.destination')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='sales.ticketsale')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to', to='sales.destination')),
            ],
        ),
    ]
