# Generated by Django 5.2.4 on 2025-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_adults_childs_infants_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='flight_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
