# Generated by Django 5.2.4 on 2025-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_ticketsale_flight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='flight_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
