# Generated by Django 5.2.4 on 2025-08-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_ticketsale_flight_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsale',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='flight_from',
        ),
        migrations.RemoveField(
            model_name='ticketsale',
            name='flight_to',
        ),
    ]
