# Generated by Django 5.2.4 on 2025-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_adults_name_alter_childs_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='no_of_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='no_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='no_of_infants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
