# Generated by Django 5.2.4 on 2025-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_ticketsale_no_of_adults_ticketsale_no_of_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='manual_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
