# Generated by Django 5.2.4 on 2025-09-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_ticketsale_manual_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('auto_cancelled', 'Auto_Cancelled'), ('self_cancelled', 'Self Cancelled'), ('no_show', 'No Show')], default='active', max_length=30),
        ),
    ]
